# Generated by Django 3.2 on 2021-04-21 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-id']},
        ),
    ]
