# Generated by Django 3.2 on 2021-04-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0004_auto_20210422_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
